### ISSUE TITLE
Add support for product patches

### ISSUE THREAD

**Issue by vzovko** [vmware-labs/vmware-customer-connect-cli#4]
It would be great if `vcc` would support downloading product patches. 

For example: 
As of now ESXi 7.0U3j has been released but is currently only available via the Product Patches site in Customer Connect.  
The latest currently available version under Product Downloads is ESXi 7.0U3g.
Even ESXi 7.0 U3i is missing in Product Download which as been released Dec 08 2022.

Thanks for this awesome tool!

**Comment by laidbackware** [comment]
@vzovko thanks for raising this. Can you provide an example URL and the workflow you use to find the patches?

**Comment by vzovko** [comment]
Typically, I get a notification that a new ESXi update has been released. What I do then is as follows:

1. Check release notes and build details: <https://docs.vmware.com/en/VMware-vSphere/7.0/rn/vsphere-esxi-70u3j-release-notes.html>
2. Log into customer connect via <https://customerconnect.vmware.com/>
3. Go to to `Products and Accounts > My Products > VMware vSphere > View Download Components`
4. Select version `7.0` and `Go to downloads` for `VMware vSphere Hypervisor (ESXi)`. Currently the latest version available there is `7.0U3g` but `7.0U3j` is already available.
5. Go to `Products and Accounts > Product Patches`.
6. Select `ESXi (Embedded and Installable)` and version `7.0`, then click `Search`.
7. The first result shows the latest release is `VMware-ESXi-7.0U3j-21053776-depot`.
8. Click `Download now` to retrieve the file.

It would be great if `vcc` could search, inspect and download those patches.

**Comment by laidbackware** [comment]
Thanks for providing further clarification. I see what's involved now and think that it would be a decent amount of work to update the SDK for this new workflow. I'll add it to the backlog, but can't commit that it will be done unless someone in the community picks it up, as vcc doesn't have the funding like you would get with an official product, meaning folks would likely be working on it during their own time.

**Comment by vzovko** [comment]
Maybe someday this project will receive funding. I'll reach out to our TAM, maybe he can spread the word around of what a useful tool you provide here.

Thanks for adding this to your backlog.
